### ISSUE TITLE
Support for directly importing WASM binary in embeded SDK

### ISSUE THREAD

**Issue by tomlewis0** [cerbos/cerbos-sdk-javascript#1010]
The `@cerbos/embedded` SDK is intended to pull wasm bundles from a remote source. This makes sense given the intended use case for Cerbos Hub (centralised updates etc) but for some platforms this isn't possible.

Cloudflare Workers is one of a few platforms with transient functions where `WebAssembly.instantiateStreaming` is [not supported](https://developers.cloudflare.com/workers/wrangler/bundling/#files-which-will-not-be-bundled:~:text=Cloudflare%20Workers%20does%20not%20support), and calling `fetch` outside of the request handler is also [not supported](https://developers.cloudflare.com/workers/runtime-apis/fetch/#:~:text=fetch()%20within%20global%20scope%20%E2%86%97). It also doesn't support calling `WebAssembly.instantiate` [with a buffer parameter](https://developers.cloudflare.com/workers/runtime-apis/web-standards/#:~:text=WebAssembly.instantiate%20with%20a%20buffer%20parameter) so we can't load wasm from a URL even in the handler (which would give poor performance anyway).

In this context, the only option is to import the wasm binary directly which is supported by Cloudflare Workers but can't be used with the SDK at the moment.

This is because the [WebAssembly.instantiate](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate_static) function has an alternative return type when importing a [WebAssembly.Module](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Module).

The most straightforward way I found to add support is to for a check for the type in the `instantiated` function.

https://github.com/cerbos/cerbos-sdk-javascript/blob/8b1c56aef352c2e9de41cd24f26c0e3d07cec2c5/packages/embedded/src/bundle.ts#L185-L189
to

```typescript
function instantiated(sourceOrInstance: WebAssembly.WebAssemblyInstantiatedSource | WebAssembly.Instance ): Exports {
  const { exports } = sourceOrInstance instanceof WebAssembly.Instance ? sourceOrInstance : sourceOrInstance.instance;
  return exports as Exports;
}
```

And to extend the `Source` type to include `WebAssembly.Module`
https://github.com/cerbos/cerbos-sdk-javascript/blob/8b1c56aef352c2e9de41cd24f26c0e3d07cec2c5/packages/embedded/src/loader.ts#L58-L64

This is an example of how it would be used in the most basic Cloudflare Worker.
```typescript
// worker/index.js
import { Embedded as Cerbos } from '@cerbos/embedded';
import wasm from './pdp.wasm'; 

const cerbos = new Cerbos(wasm);

export default {
  async fetch(request): Promise<Response> {
    const check = await cerbos.isAllowed({
      principal: {
        id: "user@example.com",
        roles: ["USER"],
        attr: { tier: "PREMIUM" },
      },
      resource: {
        kind: "document",
        id: "1",
        attr: { owner: "user@example.com" },
      },
      action: "view",
    });

    return Response.json(check);
  },
} satisfies ExportedHandler;
```

---

As an aside to this issue, using compiled wasm modules is not ideal since we don't get the benefit of centralised updates from Cerbos Hub.

I'd like to add a feature request for webhooks from Cerbos Hub which would enable us to run and update from CI. For now, we'll poll and in the same way the `AutoUpdatingLoader` does and create the webhooks ourselves.

**Comment by haines** [comment]
Released in [@cerbos/embedded v0.8.0](https://www.npmjs.com/package/@cerbos/embedded/v/0.8.0)!
