### ISSUE TITLE
Access to audit logs?

### ISSUE THREAD

**Issue by nadilas** [cerbos/cerbos-sdk-javascript#941]
Could you add the AuditLogs methods similar to the Go client?

**Comment by haines** [comment]
Yep, I'll get on that next week, it's been on the to-do list for a while!

**Comment by nadilas** [comment]
@haines awesome, I'm trying to reproduce https://github.com/cerbos/demo-admin-api/blob/main/main.go in a nuxt application through a trpc backend.

If you need a hand or someone for testing let me know.

**Comment by haines** [comment]
Hi @nadilas, I just realised I forgot to ping you when I released this, sorry! It's out now in the latest npm releases ([0.18.0 for grpc](https://www.npmjs.com/package/@cerbos/grpc/v/0.18.0), [0.19.0 for http](https://www.npmjs.com/package/@cerbos/http/v/0.19.0)) -- [here's the changelog with links to the new methods in the documentation](https://github.com/cerbos/cerbos-sdk-javascript/blob/main/packages/core/CHANGELOG.md#0180---2024-05-15).

**Comment by nadilas** [comment]
Thanks @haines, this is great!
